---
- hosts: all
  become: yes

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Packages
      apt:
        name: "{{ apt_pkgs }}"
        state: latest

    - name: Check for VS Code
      stat: 
        path: /usr/bin/code
      register: code_exists

    - name: Install VS Code
      apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
      when: not code_exists.stat.exists

    - name: Check for Chrome
      stat: 
        path: /opt/google/chrome/chrome
      register: chrome_exists
    
    - name: Install Chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: not chrome_exists.stat.exists

    - name: Check for Slack
      stat: 
        path: /usr/bin/slack
      register: slack_exists

    - name: Install Slack 
      apt:
        deb: https://downloads.slack-edge.com/releases/linux/4.22.0/prod/x64/slack-desktop-4.22.0-amd64.deb
      when: not slack_exists.stat.exists

    
    - name: Check for Signal
      stat: 
        path: /usr/bin/signal-desktop
      register: signal_exists

    - name: Install Signal
      block:
        - name: Signal - Add Public Signing Key
          ansible.builtin.apt_key:
            url: https://updates.signal.org/desktop/apt/keys.asc 
            keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
            state: present

        - name: Signal - Add repository
          ansible.builtin.apt_repository:
            repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
            state: present
        
        - name: Signal - Install
          apt: 
            update_cache: yes
            name: signal-desktop
            state: present
      when: not signal_exists.stat.exists

    - name: Check for TFSwitch
      stat:
        path: /usr/local/bin/tfswitch
      register: tf_exists

    - name: Install TFSwitch
      shell: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
      when: not tf_exists.stat.exists

    - name: Check for Git Prompt
      stat:
        path: /home/{{ user }}/.git-prompt.sh
      register: gitprompt_exists

    - name: Download git-prompt
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: /home/{{ user }}/.git-prompt.sh
        mode: "0644"
      when: not gitprompt_exists.stat.exists

    - name: Check for kubectl
      stat:
        path: /usr/bin/kubectl
      register: kubectl_exists

    - name: Install kubectl
      shell: |
        apt-get install -y apt-transport-https gnupg2 curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
        apt-get update
        apt-get install -y kubectl
      args:
        warn: false
      when: not kubectl_exists.stat.exists

    - name: Check for Minikube
      stat:
        path: /usr/bin/minikube
      register: minikube_exists

    - name: Install Minikube
      apt:
        deb:  https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      when: not minikube_exists.stat.exists

    - name: Manage .bashrc
      blockinfile:
        path: /home/{{ user }}/.bashrc
        block: |
          # Git Prompt
          source ~/.git-prompt.sh
          PS1='$(__git_ps1 "(%s)")'$PS1
          # Git Helper Functions
          function gbclean() {
            local dest="${1:-develop}"
            git fetch --all --prune && git checkout ${dest} && git merge origin/${dest} && git branch --merged | egrep -v "(^\*|master|dev|${dest})" | xargs git branch -d && git checkout - > /dev/null 2>&1
          }

          # Aliases
          alias python='python3'
          alias kc='kubectl'
      when: user is defined

  roles:
    - geerlingguy.docker
